#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.local"

banner "Jeffrey private PWA setup"

stage "Private owner identity"
say "The deployed private Site supplies a stable owner ID to every server request."
open_url "https://echo-chat-pwa.taaaaangwei.chatgpt.site/api/whoami"
step "Sign in to the private Site. Copy the userId value from the JSON page."
ask PRIVATE_AUTH_USER_ID "Paste userId:"
PRIVATE_USER_ID=$(node scripts/derive-owner-uuid.mjs "$PRIVATE_AUTH_USER_ID")
write_env PRIVATE_AUTH_USER_ID "$PRIVATE_AUTH_USER_ID"
write_env PRIVATE_USER_ID "$PRIVATE_USER_ID"

stage "Create Supabase and capture keys"
open_url "https://supabase.com/dashboard/new"
step "Create a project. Then open Project Settings → Data API and copy the Project URL."
ask NEXT_PUBLIC_SUPABASE_URL "Paste Project URL:"
step "Copy the anon/public key. It is not used by the current browser, but is reserved for future Auth."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste anon key:"
step "Open Project Settings → API Keys and copy the service_role/secret key. Never expose it to a browser."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste service role key:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

stage "Run database migration and seed"
open_url "https://supabase.com/dashboard"
step "Open your project → SQL Editor. Run the base migration, then 20260825230000_local_computer_agent.sql, 20260825235900_local_conversation_agent.sql, 20260826002000_proactive_messages.sql, and 20260826010000_service_role_privileges.sql in filename order."
step "Open supabase/seed.sql, replace both 11111111-1111-4111-8111-111111111111 values with your PRIVATE_USER_ID, then run it in SQL Editor."
warn "The migration changes database schema. Confirm you selected the new Jeffrey project, not another production project."
confirm "Migration and edited Seed completed successfully?" || { warn "Finish this stage before starting the app."; exit 1; }

stage "Enable the customer's local Codex"
step "Install Jeffrey Local on the customer's Mac and sign in to Codex with the customer's own account. No OpenAI API key is requested."
write_env AI_RUNTIME "local_codex"
write_env PREVIEW_MODE "false"
write_env LOCAL_COMPUTER_AGENT_ENABLED "true"
LOCAL_AGENT_PAIRING_SECRET="$(_existing LOCAL_AGENT_PAIRING_SECRET || openssl rand -hex 32)"
LOCAL_AGENT_DEVICE_TOKEN_SECRET="$(_existing LOCAL_AGENT_DEVICE_TOKEN_SECRET || openssl rand -hex 32)"
LOCAL_AGENT_APPROVAL_SECRET="$(_existing LOCAL_AGENT_APPROVAL_SECRET || openssl rand -hex 32)"
write_env LOCAL_AGENT_PAIRING_SECRET "$LOCAL_AGENT_PAIRING_SECRET"
write_env LOCAL_AGENT_DEVICE_TOKEN_SECRET "$LOCAL_AGENT_DEVICE_TOKEN_SECRET"
write_env LOCAL_AGENT_APPROVAL_SECRET "$LOCAL_AGENT_APPROVAL_SECRET"
write_env LOCAL_AGENT_TASK_TTL_MINUTES "15"
write_env LOCAL_AGENT_LEASE_SECONDS "60"
write_env LOCAL_AGENT_MIN_VERSION "0.1.0"
if [[ -z "$(_existing VAPID_PUBLIC_KEY || true)" || -z "$(_existing VAPID_PRIVATE_KEY || true)" ]]; then
  VAPID_JSON=$(node scripts/generate-vapid.mjs)
  VAPID_PUBLIC_KEY=$(node -e 'const value=JSON.parse(process.argv[1]);process.stdout.write(value.publicKey)' "$VAPID_JSON")
  VAPID_PRIVATE_KEY=$(node -e 'const value=JSON.parse(process.argv[1]);process.stdout.write(value.privateKey)' "$VAPID_JSON")
else
  VAPID_PUBLIC_KEY=$(_existing VAPID_PUBLIC_KEY)
  VAPID_PRIVATE_KEY=$(_existing VAPID_PRIVATE_KEY)
fi
write_env VAPID_PUBLIC_KEY "$VAPID_PUBLIC_KEY"
write_env VAPID_PRIVATE_KEY "$VAPID_PRIVATE_KEY"
write_env VAPID_SUBJECT "mailto:owner@localhost.invalid"
PROACTIVE_CRON_SECRET="$(_existing PROACTIVE_CRON_SECRET || openssl rand -hex 32)"
write_env PROACTIVE_CRON_SECRET "$PROACTIVE_CRON_SECRET"

stage "Write Jeffrey resource IDs"
say "These deterministic IDs match supabase/seed.sql."
write_env DEFAULT_CHARACTER_ID "22222222-2222-4222-8222-222222222222"
write_env DEFAULT_CONVERSATION_ID "33333333-3333-4333-8333-333333333333"
note "Local configuration is ready. Deployment uses the same values as protected Sites Secrets."
note "Web Push keys and proactive scheduler secret are ready. Configure an hourly Cloudflare Cron Trigger for the deployed Worker."

finish
